### ISSUE TITLE
Partially unable to get data using metropolitan statistical area/micropolitan statistical area geoHierarchy

### ISSUE THREAD

**Issue by ofiron01** [uscensusbureau/citysdk#345] opened 2021-06-14 09:10 UTC
Using citySDK ^2.1.5
When issuing queries similar to the following, for vintages 2015,2016,2017,2018,2019
`{
  "vintage": 2015,
  "geoHierarchy": {
    "metropolitan statistical area/micropolitan statistical area": {
      "lat": "33.9327331",
      "lng": "-84.0695961"
    }
  },
  "sourcePath": [
    "acs",
    "acs5"
  ],
  "values": [
    "B01001_001E"
  ],
  "statsKey": "9083090a7e37afe91198820867a9734ed6728718"
}`

I get valid responses for vintages 2017,2018,2019 but for 2015, 2016 - CitySDK fails with an error:
"No FIPS (Census geocodes) found for given arguments" -- which breaks my API call.
For each of my requests, I see an additional background API call and log prints are made to TigerWeb, for example (2015):

"Getting Census FIPS Geocoding data from source:"
https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2015/Mapserver//query?geometry=-84.0695961,33.9327331&geometryType=esriGeometryPoint&inSR=4269&spatialRel=esriSpatialRelIntersects&returnGeometry=false&f=pjson&outFields=

And some of these calls respond with an error (for example vintage 2015):
`{
  "error": {
    "code": 500,
    "message": "Service TIGERweb/tigerWMS_ACS2015/MapServer not started ",
    "details": []
  }
}`

*However* when issuing a direct GET request to Census API (the one is printed to the log by CitySDK), for example, vintage 2015:
https://api.census.gov/data/2015/acs/acs5?get=B01001_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:12060&key=9083090a7e37afe91198820867a9734ed6728718

It does respond with valid data so it seems something between CitySDK and TigerWeb is causing this.
Maybe I should point out I'm creating these requests asynchroniously one after the other, no waiting time between them.
Please advise, help is highly appreciated!

**Comment by ofiron01** [comment] 2021-06-14 10:49
Just noticed something that might be useful
Tigerweb calls that fail seem to be missing an argument after the Mapserver part of the URL and before the query part. example:
https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2015/**Mapserver//query**?geometry=-84.0695961,33.9327331&geometryType=esriGeometryPoint&inSR=4269&spatialRel=esriSpatialRelIntersects&returnGeometry=false&f=pjson&outFields=

where API calls that do work have this argument in place, example:
https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_ACS2017/**Mapserver/78/query**?geometry=-84.0695961,33.9327331&geometryType=esriGeometryPoint&inSR=4269&spatialRel=esriSpatialRelIntersects&returnGeometry=false&f=pjson&outFields=CBSA

**Comment by loganpowell** [comment] 2021-06-14 11:31
Hi @ofiron01. 

I think what you're running up against is the fact that pre-2017 vintages of the TigerWeb WMS (web mapping services) - which power the geocoding functionality of CitySDK - have been removed.

I apologize for any inconvenience this may have caused you.

Logan

**Comment by ofiron01** [comment] 2021-06-14 11:42
@loganpowell thanks for your reply. Then how would I go about querying data for prior 2017 based on metropolitan statistical area geo-hierarchy? assuming all I have is lat/lng and maybe a zip code.  How do I convert this to the metro code (12060 in my examples) in order to get the right geography.

**Comment by loganpowell** [comment] 2021-06-14 12:17
Unfortunately, the CitySDK is only as complete as it's underlying services, which include the WMS servers. If you'd like to ping the TigerWeb team to see if they might consider replacing earlier vintages, send an email to geo.geography@census.gov and copy me logan.t.powell@census.gov. Be as specific about your need as possible.

**Comment by ofiron01** [comment] 2021-06-15 07:33
Sent an email with you as CC, thanks. Maybe it's a good idea to update the readme file with this
https://github.com/uscensusbureau/citysdk#geographies-available-by-vintage

**Comment by loganpowell** [comment] 2021-06-15 12:17
I realize some of the examples do indeed need to be corrected to accommodate the deprecated WMS servers. I will also specify which are available in the [geocoding section](https://github.com/uscensusbureau/citysdk#geocoding-latitudelongitude---fips-code), but the cartographic files (GeoJSON) availability hasn't changed.

Thank you for the report.

**Comment by ruiz0001** [comment] 2021-06-15 13:06
We apologize for the removal of the older WMS services. This was a mistake on our part. We'll work on restoring the older services. Unfortunately, this may take a few weeks.

Sorry for the inconvenience,


________________________

Ricardo J Ruiz, PMP, Assistant Division Chief

Spatial Data Systems, Decennial Information Technology Division

U.S. Census Bureau

O: 301-763-8975 | M: 301-367-8689

census.gov<https://www.census.gov/en.html> | @uscensusbureau<https://www.census.gov/about/contact-us/social_media.html> | 2020census.gov<https://2020census.gov/>

________________________________

**Comment by loganpowell** [comment] 2021-06-15 15:41
That's great news @ruiz0001 🥇

**Comment by ofiron01** [comment] 2021-06-15 15:47
@ruiz0001 That's awesome! I'd appreciate it if you update here once something changes so we can approach this again. Can we get more precise time estimation🙄? @loganpowell can we keep this open for tracking purposes?

**Comment by ruiz0001** [comment] 2021-06-15 18:52
We are estimating that the older WMS services will be restored by the end of June.


________________________

Ricardo J Ruiz, PMP, Assistant Division Chief

Spatial Data Systems, Decennial Information Technology Division

U.S. Census Bureau

O: 301-763-8975 | M: 301-367-8689

census.gov<https://www.census.gov/en.html> | @uscensusbureau<https://www.census.gov/about/contact-us/social_media.html> | 2020census.gov<https://2020census.gov/>

________________________________

**Comment by loganpowell** [comment] 2021-06-15 18:58
Yes, we'll keep it open

**Comment by loganpowell** [comment] 2021-06-15 19:00
@ruiz0001 if it's not too much trouble, while you're backfilling, can the [2020 State Legislative Districts- Lower Chamber](https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Census2020/MapServer) be added? Currently there is a duplicate of the Upper Chamber for that vintage:
https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Census2020/MapServer

**Comment by ruiz0001** [comment] 2021-06-15 19:45
Sure thing.

Ricky


________________________

Ricardo J Ruiz, PMP, Assistant Division Chief

Spatial Data Systems, Decennial Information Technology Division

U.S. Census Bureau

O: 301-763-8975 | M: 301-367-8689

census.gov<https://www.census.gov/en.html> | @uscensusbureau<https://www.census.gov/about/contact-us/social_media.html> | 2020census.gov<https://2020census.gov/>

________________________________

**Comment by loganpowell** [comment] 2021-06-15 19:45
Thanks boss man

**Comment by ofiron01** [comment] 2021-06-28 08:37
Hi @ruiz0001 Any update regarding this? 🙏

**Comment by loganpowell** [comment] 2021-07-12 19:03
Hi @ruiz0001 do we have news on this front?

**Comment by ruiz0001** [comment] 2021-07-12 19:40
I replied on 6/29 via email. Looks like something went wrong. In any case, here is my response:

We restored the map services for ACS 2012 through 2016 as of last night, June 28. Please, let us know if you have any other problems with these services.

Again, our apologies for the inconvenience caused by the time the map services were unavailable.

I should add that the issues with the 2020 SLDs were resolved as well.

**Comment by loganpowell** [comment] 2021-07-12 20:48
That is great news!

**Comment by loganpowell** [comment] 2021-07-14 14:50
Closing as resolved

**Closed by loganpowell** 2021-07-14 14:50 UTC
