### ISSUE TITLE
Currently getting errors on CitySDK JS Library, X origin restricted

### ISSUE THREAD

**Issue by kuanb** [uscensusbureau/citysdk#231] opened 2016-02-19 02:07 UTC
Getting the following result:

XMLHttpRequest cannot load http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/86/query. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'localhost' is therefore not allowed access.

Anyone else getting this?

If you go to that URL, it reroutes to: http://outage.census.gov/restricted.html
That page states: "The system you have attempted to reach is for restricted use only and is not permitted from your source address."

Perhaps it is a Census outage?

**Comment by kuanb** [comment] 2016-02-19 02:23
Here's an example of a simple request being performed with City SDK and the error occuring:

![image](https://cloud.githubusercontent.com/assets/6053396/13164776/102def68-d675-11e5-8e47-1d82f57f3f06.png)

**Comment by kuanb** [comment] 2016-02-19 17:13
According to whomever runs the US Census Bureau Twitter acct: 

"The site is currently unavailable due to maintenance. We are working to have the site back online as quickly as possible."

That said, we are in at least day 2 and there seems to be no service update...

Src: https://twitter.com/buttsmeister/status/700503974927937536

**Comment by logantpowell** [comment] 2016-02-19 17:27
Hi @kuanb let me try to route your issue to the right parties... Can you email me at: logan.t.powell@census.gov with what you're trying to accomplish and with what service and I'll forward it directly to the folks that need to see it (looks like tigerweb)?

**Comment by ruiz0001** [comment] 2016-02-19 18:44
See below for notification we received last night about TIGERweb.  This is all the information I have.


Thanks,


Ricardo J Ruiz, PMP, Chief, Spatial Products Systems Branch, Decennial Information Technology Division, U.S. Census Bureau

Office 301.763.8975   Cell 301.367.8689   Fax 301.763.4710   Ricardo.J.Ruiz@census.gov

census.gov<http://www.census.gov/>   Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>


________________________________
From: Earl Campbell (CENSUS/DITD FED)
Sent: Thursday, February 18, 2016 6:20 PM
To: GEO DOWNTIME List
Cc: Earl Campbell (CENSUS/DITD FED)
Subject: GEO-Downtime [****Effective Immediately - TIGERweb, Data Mapper, and Flows Mapper Public Access Unavailable Until Further Notice****]

Please be advised that until further notice IT has disabled access to the TIGERweb, Data Mapper, and Flows Mapper.

The applications will remain available for internal Census use only.  There is no ETA for when the public access to these applications will be restored.  Additional notifications will be sent out when the applications become available.
Thanks,

Earl M. Campbell
IT Specialist / System Administrator
Geospatial Technology Services Branch
Decennial Information Technology Division
U.S. Census Bureau
Phone: 301-763-5286
Email: earl.campbell@census.gov
census.gov<http://www.census.gov/>
Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>



________________________________

**Comment by logantpowell** [comment] 2016-02-19 18:46
Thank you @ruiz0001!

**Comment by ebrelsford** [comment] 2016-02-27 18:50
Is there any chance of putting a notice on the documentation pages to this effect?

**Comment by logantpowell** [comment] 2016-03-02 14:39
@ebrelsford we're currently undergoing quite a bit of internal organizational configuration to get these issues checked on and reported out quicker. It's still very much an alpha project, but please have patience with us as we work out these kinks.  We're currently trying to figure out how to build in some redundancy for these services so we won't have to send out notices as frequently, but I'd also recommend anyone having issues to send them to our twitter handle @uscensusbureau. It's not ideal, but that seems to rally the fasted response from the organization.

**Comment by kuanb** [comment] 2016-03-07 21:20
Hi @logantpowell apologies for delay is email still necessary? The whole process also played out over Twitter which generated some response (much appreciated). 

From what I can see of copied email, looks like this component is out/off at the moment (Tiger Web). What does this mean for operability of City SDK moving forward?

**Comment by logantpowell** [comment] 2016-03-08 19:22
@kuanb we're working on a contingency plan for such incidents moving forward and really appreciate your patience as a user. Don't give up on us!

**Comment by zachmaurer** [comment] 2016-04-02 06:04
Still getting the same errors -- any ideas?
Is outage.census.gov actually up to date right now? 

It lists the US Census Bureau as shutdown until further notice...

**Comment by jmeisel** [comment] 2016-04-02 19:06
I'm not able to replicate your issue.  If I understand the question -- you
are saying that the TIGERweb service is down.  However this is working for
me:
http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/86/query

and I ran a few of the CitySDK built in examples and is appears to be
working.

Note that outage.census.gov is not accurate, that is a separate issues I am
dealing with.  However please advise if this is still unresolved.

**Comment by ruiz0001** [comment] 2016-04-04 12:51
If user is still seeing the Outage message when trying to access TIGERweb, more than likely, they need to clear their browser cache to solve the problem.


Thanks,


Ricardo J Ruiz, PMP, Chief, Spatial Products Systems Branch, Decennial Information Technology Division, U.S. Census Bureau

Office 301.763.8975   Cell 301.367.8689   Fax 301.763.4710   Ricardo.J.Ruiz@census.gov

census.gov<http://www.census.gov/>   Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>


________________________________

**Comment by lucianoiscool** [comment] 2016-04-15 07:50
I had the same issue. 

The problem seems to be related to a difference between the citysdk.census.js file used in the examples website, [available here](https://github.com/uscensusbureau/citysdk/blob/gh-pages/static/js/citysdk/citysdk.census.js), and the current file on master, [here](https://github.com/uscensusbureau/citysdk/blob/master/js/citysdk.census.js).  The difference comes in on line 34. Here is what it looks like.
 
<img width="1124" alt="screen shot 2016-04-15 at 3 35 54 am" src="https://cloud.githubusercontent.com/assets/2956449/14554489/5d1ba6ea-02bb-11e6-8094-e00e9224bd22.png">

So if you simply point your file to `https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/` it works. (although ssl should be enabled by default on CitySDK anyway but I haven't looked into this)

**But here's the weird/tricky part**. After you change to the `https` site once and then you remove the `https` to attempt to recreate the issue, the bug is not reproduced.  Not sure why but might have something to do with being added to some sort of whitelist :/ .

@jmeisel To try to reproduce the bug you have to first remove the `https`, or use the file in the master branch. Then you have to add a new new hostname to `/etc/hosts/` that points to your localhost. Then using this new hostname and attempt to use the CitySDK.

**Comment by wbconnelly** [comment] 2016-04-22 13:41
Just FYI this is still an issue.  The version of the CitySDK module you are instructed to load on the CitySDK demo on the site is different from the version they are loading themselves to run the demo. Very confusing.

**Comment by logantpowell** [comment] 2016-04-22 13:46
@johnson-tor-boozallen can we resolve this so we can close this issue?

**Comment by wbconnelly** [comment] 2016-04-22 16:03
Have the links to the sdk libraries been disabled?  Now my code won't run al all.

**Comment by johnson-tor-boozallen** [comment] 2016-04-22 18:43
The RawGit CDN caches things permanently and shouldn't ever disable.  

In responding to @lucianoiscool 's note that the bug doesn't reproduce, I can help there as well.  The CitySDK aggressively caches data in the browser's IndexedDB.  If it succeeded at any point, the data will be saved and the same request will not be made to the server again.

**Comment by johnson-tor-boozallen** [comment] 2016-04-22 20:41
We just updated all the code examples so that they no longer reference older versions of the SDK on the rawgit CDN.

**Comment by rlucas92** [comment] 2016-05-02 17:20
So I was getting the same error as kuanb, and I confirmed that opening http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/86/query in a browser tab did indeed work. So that site is not down.

What fixed it for me, is pointing to the citySdk.js libraries that are hosted on the examples page.

The instructions at http://uscensusbureau.github.io/citysdk/gettingstarted.html tell you to use:
```
<script src="https://cdn.rawgit.com/uscensusbureau/citysdk/Release1.1/js/citysdk.js"></script>
<script src="https://cdn.rawgit.com/uscensusbureau/citysdk/Release1.1/js/citysdk.census.js"></script>
```

Instead, I used 
```
<script src="http://uscensusbureau.github.io/citysdk/static/js/citysdk/citysdk.js"></script>
<script src="http://uscensusbureau.github.io/citysdk/static/js/citysdk/citysdk.census.js"></script>
```
which fixed the error I was getting.

**Comment by michael2million** [comment] 2016-08-03 15:51
Several of the examples at CitySDK do not work. 

For example here: https://uscensusbureau.github.io/citysdk/guides.html

It just returns CitySDK as undefined.

CitySDK needs updated instructions on Getting Started, because obviously there have been a number of changes and my application is now broken and getting errors.

This example works to pull GeoJSON shapes, but doesn't add the geographic data to the pop-ups: https://uscensusbureau.github.io/citysdk/examples/containerGeometry/

There are lots of cases like this across the documentation. Is this project being maintained? Seems very odd for the US Govt Census, a pretty major repository of data, to have these unresolved issues for so long... What's going on?

**Comment by logantpowell** [comment] 2016-08-03 17:35
Hi @michael2million very sorry for the broken examples... we just lost our developer at the same time as we've released a major update. We are seeking a sustainable solution to our situation, but I would like to ensure you that both the SDK and Node API are functional.

**Comment by loganpowell** [comment] 2018-12-20 15:32
new version (v2) should work. It's now an NPM library and has removed this barrier. New examples can be found here:

http://uscensusbureau.github.io/citysdk/examples/

note that the runkit examples are throttled (very throttled), so give it a spin with `npm install citysdk` and let us know what you think!

**Closed by loganpowell** 2018-12-20 15:32 UTC
